### ISSUE TITLE
Plausible tracking internal links as "outbound clicks

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#818] opened 2023-03-31 02:52 UTC
![image](https://user-images.githubusercontent.com/10799815/229010739-5e339231-2349-41fb-8733-1427e88844a0.png)

**Comment by paulschreiber** [comment] 2023-04-07 17:50
Your screen shot has one example of an internal link: `/tools/story-maps`.

I can't reproduce the problem. I suspect it was fixed with https://github.com/techmatters/terraso-web-client/pull/823

**Closed by paulschreiber** 2023-04-07 17:50 UTC
Labels: 1000L, Engineering

**Comment by DerekCaelin** [comment] 2023-04-07 18:08
thank you
