### ISSUE TITLE
Bison Hillock landscape boundary is missing 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#283] opened 2022-03-28 22:09 UTC
## Description
Bison Hillock landscape boundary is not properly rendered.

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: https://app.terraso.org/landscapes/bison-hillock
2. See the landscape map with an error indicator

## Expected behavior
the landscape boundary is displayed on the map. See other landscapes as reference: 
https://app.terraso.org/landscapes/umngeni

## Actual behavior
<img width="583" alt="image" src="https://user-images.githubusercontent.com/92342777/160494770-b1dae154-800f-4898-bc9e-2810fd557c94.png">

**Comment by paulschreiber** [comment] 2022-03-29 14:05
@DerekCaelin is this a duplicate of #280?

**Comment by DerekCaelin** [comment] 2022-03-30 18:41
It looks like a different issue.

**Comment by DerekCaelin** [comment] 2022-03-30 18:42
An updated .geojson file is available [here](https://airtable.com/appIE3c0ExjlY2N7l/tblnmj9Dv0GJJIhAm/viwETromIx4i5uRCU/rec7fLUCIszEoyQZj?blocks=hide).

**Closed** 2022-03-31 17:17 UTC
