### ISSUE TITLE
increasingly load time as landscape number increases

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#728] opened 2023-02-24 20:54 UTC
The load time for the Landscapes tab is high, consistently about 10 seconds. This happens every time I navigate back to the landscapes page. On staging, we have 92 landscapes. 

The delay appears to be in the server response time. 

https://user-images.githubusercontent.com/10799815/221287926-37db7b37-5e20-4ea1-8756-319c64461067.mov

<img width="419" alt="image" src="https://user-images.githubusercontent.com/10799815/221288443-e33d28a8-d6f3-4ac0-87ee-030db47796e5.png">

Less pronounced but still a long wait is the home screen. 

https://user-images.githubusercontent.com/10799815/221288721-4a76d091-f55b-4430-9563-5ba963d5ced7.mov

**Comment by paulschreiber** [comment] 2023-02-24 20:57
This is a duplicate of #665.

**Closed by paulschreiber** 2023-02-24 20:57 UTC
