### ISSUE TITLE
Story Maps: subtitle text size is larger than the title text size

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#754] opened 2023-03-09 18:16 UTC
## Description
Subtitle text should be displayed smaller than the Story map title to set the proper information hierarchy. 

## Steps To Reproduce

1. https://app.staging.terraso.net/tools/story-maps/new
2. Enter text to Story map title field
3. Enter text to Story map subtitle field
4. Notice how those two text displayed 

## Expected behavior
<img width="367" alt="image" src="https://user-images.githubusercontent.com/92342777/224119561-b0988a76-fe61-4819-9736-fd21a46a4eb3.png">

## Actual behavior
<img width="369" alt="subtitle text size" src="https://user-images.githubusercontent.com/92342777/224118994-852d0cc4-5b6e-4c0f-893f-f07dfbcb0a12.png">

**Comment by jodiezhuu** [comment] 2023-05-19 15:51
Looks like the issue is fixed in staging; title and subtitle text size are following the expected behaviour: 
<img width="370" alt="Screen Shot 2023-05-19 at 11 51 27 AM" src="https://github.com/techmatters/terraso-web-client/assets/82774370/caa4c577-0ce9-42a4-82f0-4fed01913e2e">

**Closed** 2023-05-19 15:51 UTC
Labels: 1000L, Engineering
