### ISSUE TITLE
Leave a landscape, but still see that I am a member in home

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#179] opened 2022-01-25 14:26 UTC
## Description
I removed myself from a landscape, Acus Galera San Francisco, but I still see that I am a member on the home screen.

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Go to URL: https://app.terraso.org/landscapes/acus-peninsula-galera-san-francisco
2. Click on 'Leave Landscape'
3. Return to home
4. See that I am still a member of the landscape

## Expected behavior
I expected to see that I was a member of no landscapes.

## Actual behavior
I see that I am still a member of ACUS Galera San Francisco

**Comment by cacarrara** [comment] 2022-01-27 17:49
The PR below touched on Group filtering and it seems the issue is fixed now. I couldn't reproduce it anymore on staging. I'm closing it but feel welcome to reopen it if you see any problem @DerekCaelin 

- https://github.com/techmatters/terraso-backend/pull/101

**Closed by cacarrara** 2022-01-27 17:49 UTC
Labels: Medium

**Comment by DerekCaelin** [comment] 2022-01-27 17:56
I longer encounter this problem in production!
