### ISSUE TITLE
"Shared Files" module does not appear until refresh

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#357] opened 2022-05-24 19:45 UTC
## Description
If I join a group from the group's page, the files module does not appear until refresh

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. View group list
2. Go to group page (do not join)
3. Join group

## Expected behavior
Files module should appear

## Actual behavior
Files module does not appear until refresh

**Comment by paulschreiber** [comment] 2022-05-24 20:20
This is a duplicate of #344

**Closed by paulschreiber** 2022-05-24 20:20 UTC
Labels: Medium
