### ISSUE TITLE
Can't upload csv file with Shared Files module

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-web-client#479] opened 2022-07-29 15:03 UTC
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/10799815/181787852-cd9d1f67-07ca-4ac9-bb94-027354bcbdc4.png">

## Description
I tried to upload [a csv file](https://drive.google.com/file/d/1EbIZP6VRMKer8n68eqYInxI1srauo8MF/view?usp=sharing) to the [Rocky Hill Sustainability Team](https://app.terraso.org/groups/rocky-hill-sustainability-team) on Terraso. After trying to submit, I received the error message:  `The file extension (.csv) does not match the file's contents`

I am able to open the file in Excel without problems.

**Comment by paulschreiber** [comment] 2022-07-29 15:51
This is a duplicate of https://github.com/techmatters/terraso-backend/issues/171

Because the file only has one column, it is not seen as a valid CSV.

**Closed by paulschreiber** 2022-07-29 15:51 UTC
Labels: High
