### ISSUE TITLE
Story map: Default map should be the one from the previous chapter 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#691] opened 2023-02-13 15:53 UTC
## Description
After setting the background map for the chapter 1, I saw the same map when the chapter 2 was added in the Edit view. 
But when entered the map view, the globe map (default for the Title chapter) was shown. 

## Steps To Reproduce

1. Enter Story map view : https://app.staging.terraso.net/tools/story-maps/create
2. Add a new chapter and enter text for title
3. Set the map view for chapter 1. e.g. USA 
4. Add a new chapter, chapter 2
5. Note the same map I set for the chapter 1 is shown.
6. Click ' Set location map for this chapter'
7. Notice the globe map is shown instead of USA map. 

## Expected behavior
The map I saw before entering the Set Background screen.

## Actual behavior
<img width="652" alt="image" src="https://user-images.githubusercontent.com/92342777/218525174-babc574a-6d01-415d-b763-5fe4714a8529.png">

**Comment by josebui** [comment] 2023-02-13 23:19
@Hanal-code This should be fixed now

**Comment by DerekCaelin** [comment] 2023-02-14 15:38
I confirm that this works. Thanks Jose!

**Comment by DerekCaelin** [comment] 2023-02-15 22:13
Reopening this. The issue was resolved, but after we made it possible to add a location for the title screen, this feature doesn't work for chapter 1.

**Comment by josebui** [comment] 2023-02-15 23:06
@DerekCaelin are you using the same repro steps? I can't reproduce this

**Comment by DerekCaelin** [comment] 2023-02-16 19:54
Sorry, I wasn't clear. Here is how to produce the error. 

https://user-images.githubusercontent.com/10799815/219472313-6b1a79b3-aef5-4fd3-a748-ef1ebc23c657.mov

1. Set the location for the title screen (zoom in to a location)
2. Create chapter 1
3. Click the button to "Set location map for this chapter"
4. Note that the map defaults to the globe view rather than the zoomed in location from the title screen

**Comment by josebui** [comment] 2023-02-16 20:44
@DerekCaelin This should be fixed on staging now

**Comment by DerekCaelin** [comment] 2023-02-24 19:41
Confirmed!

**Closed by DerekCaelin** 2023-02-24 19:41 UTC
Labels: High
