### ISSUE TITLE
Landscape Profile help popover text have different font

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-web-client#646] opened 2023-01-06 21:43 UTC
## Description
Inconsistent font used in Help popover in the profile form.

## Steps To Reproduce

1. Go to: https://app.staging.terraso.net/landscapes/0106-2023-take2/profile/edit
3. Open the ECOSYSTEM TYPES help text. Note the font is the system font .
4. Open the LANGUAGES help text. Note the selected font is Roboto.

## Expected behavior
**EXPECTED:**
`font-family: Roboto, Helvetica, Arial, sans-serif;
`
<img width="665" alt="image" src="https://user-images.githubusercontent.com/92342777/211104706-a742e662-8d4d-4590-8044-f12d1dac9a06.png">

## Actual behavior
**CURRENT** 
`font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif;`
<img width="824" alt="image" src="https://user-images.githubusercontent.com/92342777/211104648-b88aa191-bf16-45e3-9293-d2000d616843.png">

**Comment by paulschreiber** [comment] 2023-01-19 16:46
I can't reproduce this locally or on staging. Closing.

**Closed by paulschreiber** 2023-01-19 16:46 UTC
